/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_histocv_lib_HistoOpenCv */

#ifndef _Included_org_histocv_lib_HistoOpenCv
#define _Included_org_histocv_lib_HistoOpenCv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_histocv_lib_HistoOpenCv
 * Method:    writeHistogram
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_histocv_lib_HistoOpenCv_writeHistogram
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
