FROM postgres:9.6

LABEL version="0.0.1-beta"
LABEL name="poc-datamodel-postgres"
LABEL release-date="2017-02-04"
LABEL description="PostgreSQL 9.6  used in poc-datamodel"

RUN localedef -i pt_BR -c -f UTF-8 -A /usr/share/locale/locale.alias pt_BR.utf-8

ENV LANG pt_BR.utf8
